<?php

namespace AppBundle\Repository;

/**
 * AdminTransactionDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminTransactionDataRepository extends \Doctrine\ORM\EntityRepository
{
}
