<?php

namespace AppBundle\Repository;

/**
 * csvLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class csvLogsRepository extends \Doctrine\ORM\EntityRepository
{
}
