<?php

namespace AppBundle\Repository;

/**
 * MainCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
