<?php

namespace AppBundle\Repository;

/**
 * MenuItemParentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemParentRepository extends \Doctrine\ORM\EntityRepository
{
}
