<?php

namespace AppBundle\Repository;

/**
 * OrderItemExtrasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemExtrasRepository extends \Doctrine\ORM\EntityRepository
{
}
