<?php

namespace AppBundle\Repository;

/**
 * PackageExtrasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackageExtrasRepository extends \Doctrine\ORM\EntityRepository
{
}
