<?php

namespace AppBundle\Repository;

/**
 * PromocodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromocodeRepository extends \Doctrine\ORM\EntityRepository
{
}
