<?php

namespace AppBundle\Repository;

/**
 * RestaurantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantsRepository extends \Doctrine\ORM\EntityRepository
{
}
