<?php

namespace AppBundle\Repository;

/**
 * RestaurantTransactionDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantTransactionDataRepository extends \Doctrine\ORM\EntityRepository
{
}
