<?php

namespace AppBundle\Repository;

/**
 * UserAccountsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAccountsRepository extends \Doctrine\ORM\EntityRepository
{
}
