<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Customer extends \AppBundle\Entity\Customer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'mobileNumber', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'username', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'gst', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'membership', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'area', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'ip', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'createdDate', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'channel', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'device', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'latitude', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'longitude', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'isActive', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'branch', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'isOnline', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'roles', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'apiKey', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'otp', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'path', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'file', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'registrationKey', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'billingAddress', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'restaurantRatings', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'customerOrder', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'promocode', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'promoUsage'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'mobileNumber', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'username', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'gst', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'membership', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'area', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'ip', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'createdDate', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'channel', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'device', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'latitude', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'longitude', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'isActive', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'branch', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'isOnline', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'roles', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'apiKey', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'otp', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'path', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'file', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'registrationKey', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'billingAddress', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'restaurantRatings', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'customerOrder', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'promocode', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'promoUsage'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Customer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setBranch($branch)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBranch', [$branch]);

        return parent::setBranch($branch);
    }

    /**
     * {@inheritDoc}
     */
    public function getBranch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBranch', []);

        return parent::getBranch();
    }

    /**
     * {@inheritDoc}
     */
    public function getIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIp', []);

        return parent::getIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setIp($ip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIp', [$ip]);

        return parent::setIp($ip);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', []);

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate($createdDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', [$createdDate]);

        return parent::setCreatedDate($createdDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDevice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDevice', []);

        return parent::getDevice();
    }

    /**
     * {@inheritDoc}
     */
    public function setDevice($device)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDevice', [$device]);

        return parent::setDevice($device);
    }

    /**
     * {@inheritDoc}
     */
    public function getChannel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChannel', []);

        return parent::getChannel();
    }

    /**
     * {@inheritDoc}
     */
    public function setChannel($channel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChannel', [$channel]);

        return parent::setChannel($channel);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setArea($area)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArea', [$area]);

        return parent::setArea($area);
    }

    /**
     * {@inheritDoc}
     */
    public function getArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArea', []);

        return parent::getArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude($latitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', [$latitude]);

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', []);

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude($longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', [$longitude]);

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getGst()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGst', []);

        return parent::getGst();
    }

    /**
     * {@inheritDoc}
     */
    public function setGst($gst)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGst', [$gst]);

        return parent::setGst($gst);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', []);

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setMembership($membership)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMembership', [$membership]);

        return parent::setMembership($membership);
    }

    /**
     * {@inheritDoc}
     */
    public function getMembership()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMembership', []);

        return parent::getMembership();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobileNumber($mobileNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobileNumber', [$mobileNumber]);

        return parent::setMobileNumber($mobileNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobileNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobileNumber', []);

        return parent::getMobileNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', []);

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsOnline($isOnline)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsOnline', [$isOnline]);

        return parent::setIsOnline($isOnline);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsOnline()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsOnline', []);

        return parent::getIsOnline();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles($roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setApiKey($apiKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApiKey', [$apiKey]);

        return parent::setApiKey($apiKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getApiKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApiKey', []);

        return parent::getApiKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPath', []);

        return parent::getPath();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', []);

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoorDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoorDir', []);

        return parent::getRoorDir();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', []);

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileDirPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileDirPath', []);

        return parent::getProfileDirPath();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpload', []);

        return parent::preUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', []);

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function removeUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUpload', []);

        return parent::removeUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function setPath($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPath', [$path]);

        return parent::setPath($path);
    }

    /**
     * {@inheritDoc}
     */
    public function addBillingAddress(\AppBundle\Entity\BillingAddress $billingAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBillingAddress', [$billingAddress]);

        return parent::addBillingAddress($billingAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBillingAddress(\AppBundle\Entity\BillingAddress $billingAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBillingAddress', [$billingAddress]);

        return parent::removeBillingAddress($billingAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress', []);

        return parent::getBillingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setOtp($otp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOtp', [$otp]);

        return parent::setOtp($otp);
    }

    /**
     * {@inheritDoc}
     */
    public function getOtp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOtp', []);

        return parent::getOtp();
    }

    /**
     * {@inheritDoc}
     */
    public function addRestaurantRating(\AppBundle\Entity\RestaurantRatings $restaurantRating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRestaurantRating', [$restaurantRating]);

        return parent::addRestaurantRating($restaurantRating);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRestaurantRating(\AppBundle\Entity\RestaurantRatings $restaurantRating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRestaurantRating', [$restaurantRating]);

        return parent::removeRestaurantRating($restaurantRating);
    }

    /**
     * {@inheritDoc}
     */
    public function getRestaurantRatings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRestaurantRatings', []);

        return parent::getRestaurantRatings();
    }

    /**
     * {@inheritDoc}
     */
    public function addCustomerOrder(\AppBundle\Entity\CustomerOrder $customerOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCustomerOrder', [$customerOrder]);

        return parent::addCustomerOrder($customerOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCustomerOrder(\AppBundle\Entity\CustomerOrder $customerOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCustomerOrder', [$customerOrder]);

        return parent::removeCustomerOrder($customerOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerOrder', []);

        return parent::getCustomerOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistrationKey($registrationKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistrationKey', [$registrationKey]);

        return parent::setRegistrationKey($registrationKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationKey', []);

        return parent::getRegistrationKey();
    }

    /**
     * {@inheritDoc}
     */
    public function addPromocode(\AppBundle\Entity\Promocode $promocode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPromocode', [$promocode]);

        return parent::addPromocode($promocode);
    }

    /**
     * {@inheritDoc}
     */
    public function removePromocode(\AppBundle\Entity\Promocode $promocode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePromocode', [$promocode]);

        return parent::removePromocode($promocode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromocode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromocode', []);

        return parent::getPromocode();
    }

    /**
     * {@inheritDoc}
     */
    public function addPromoUsage(\AppBundle\Entity\PromoUsage $promoUsage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPromoUsage', [$promoUsage]);

        return parent::addPromoUsage($promoUsage);
    }

    /**
     * {@inheritDoc}
     */
    public function removePromoUsage(\AppBundle\Entity\PromoUsage $promoUsage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePromoUsage', [$promoUsage]);

        return parent::removePromoUsage($promoUsage);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromoUsage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromoUsage', []);

        return parent::getPromoUsage();
    }

}
