<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MenuItem extends \AppBundle\Entity\MenuItem implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'itemName', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'nested', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'branch', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'itemPriority', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'type', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'delivery', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'maxItem', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'totalQty', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'itemSlug', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'vegType', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'itemShortDescription', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'itemDescription', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'brand', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'itemFeaturedImage', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'itemFeaturedImageFile', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'regularPrice', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'salePrice', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'isActive', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'isSubscription', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'salesTax', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'priceVariation', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'alert', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'duration', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'category', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'extraPackage'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'itemName', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'nested', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'branch', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'itemPriority', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'type', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'delivery', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'maxItem', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'totalQty', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'itemSlug', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'vegType', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'itemShortDescription', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'itemDescription', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'brand', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'itemFeaturedImage', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'itemFeaturedImageFile', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'regularPrice', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'salePrice', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'isActive', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'isSubscription', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'salesTax', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'priceVariation', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'alert', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'duration', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'category', '' . "\0" . 'AppBundle\\Entity\\MenuItem' . "\0" . 'extraPackage'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MenuItem $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemName($itemName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemName', [$itemName]);

        return parent::setItemName($itemName);
    }

    /**
     * {@inheritDoc}
     */
    public function setBranch($branch)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBranch', [$branch]);

        return parent::setBranch($branch);
    }

    /**
     * {@inheritDoc}
     */
    public function getBranch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBranch', []);

        return parent::getBranch();
    }

    /**
     * {@inheritDoc}
     */
    public function getItemPriority()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemPriority', []);

        return parent::getItemPriority();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemPriority($itemPriority)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemPriority', [$itemPriority]);

        return parent::setItemPriority($itemPriority);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrand', []);

        return parent::getBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrand($brand)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrand', [$brand]);

        return parent::setBrand($brand);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelivery()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelivery', []);

        return parent::getDelivery();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelivery($delivery)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelivery', [$delivery]);

        return parent::setDelivery($delivery);
    }

    /**
     * {@inheritDoc}
     */
    public function getNested()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNested', []);

        return parent::getNested();
    }

    /**
     * {@inheritDoc}
     */
    public function setNested($nested)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNested', [$nested]);

        return parent::setNested($nested);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuration', []);

        return parent::getDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuration($duration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuration', [$duration]);

        return parent::setDuration($duration);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlert()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlert', []);

        return parent::getAlert();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlert($alert)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlert', [$alert]);

        return parent::setAlert($alert);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemName', []);

        return parent::getItemName();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemSlug($itemSlug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemSlug', [$itemSlug]);

        return parent::setItemSlug($itemSlug);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemSlug', []);

        return parent::getItemSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxItem($maxItem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxItem', [$maxItem]);

        return parent::setMaxItem($maxItem);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxItem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxItem', []);

        return parent::getMaxItem();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalQty($totalQty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalQty', [$totalQty]);

        return parent::setTotalQty($totalQty);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalQty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalQty', []);

        return parent::getTotalQty();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemShortDescription($itemShortDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemShortDescription', [$itemShortDescription]);

        return parent::setItemShortDescription($itemShortDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemShortDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemShortDescription', []);

        return parent::getItemShortDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemDescription($itemDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemDescription', [$itemDescription]);

        return parent::setItemDescription($itemDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemDescription', []);

        return parent::getItemDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegularPrice($regularPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegularPrice', [$regularPrice]);

        return parent::setRegularPrice($regularPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegularPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegularPrice', []);

        return parent::getRegularPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalePrice($salePrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalePrice', [$salePrice]);

        return parent::setSalePrice($salePrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalePrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalePrice', []);

        return parent::getSalePrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalesTax($salesTax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalesTax', [$salesTax]);

        return parent::setSalesTax($salesTax);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalesTax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalesTax', []);

        return parent::getSalesTax();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemFeaturedImageFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemFeaturedImageFile', [$file]);

        return parent::setItemFeaturedImageFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemFeaturedImageFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemFeaturedImageFile', []);

        return parent::getItemFeaturedImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemFeaturedImage($itemFeaturedImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemFeaturedImage', [$itemFeaturedImage]);

        return parent::setItemFeaturedImage($itemFeaturedImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemFeaturedImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemFeaturedImage', []);

        return parent::getItemFeaturedImage();
    }

    /**
     * {@inheritDoc}
     */
    public function preFeaturedImageUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preFeaturedImageUpload', []);

        return parent::preFeaturedImageUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function iconUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'iconUpload', []);

        return parent::iconUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsoluteItemFeaturedImagePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsoluteItemFeaturedImagePath', []);

        return parent::getAbsoluteItemFeaturedImagePath();
    }

    /**
     * {@inheritDoc}
     */
    public function removeFeaturedImageUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFeaturedImageUpload', []);

        return parent::removeFeaturedImageUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', []);

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsSubscription($isSubscription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsSubscription', [$isSubscription]);

        return parent::setIsSubscription($isSubscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsSubscription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsSubscription', []);

        return parent::getIsSubscription();
    }

    /**
     * {@inheritDoc}
     */
    public function addPriceVariation(\AppBundle\Entity\PriceVariation $priceVariation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPriceVariation', [$priceVariation]);

        return parent::addPriceVariation($priceVariation);
    }

    /**
     * {@inheritDoc}
     */
    public function removePriceVariation(\AppBundle\Entity\PriceVariation $priceVariation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePriceVariation', [$priceVariation]);

        return parent::removePriceVariation($priceVariation);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceVariation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceVariation', []);

        return parent::getPriceVariation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory($category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function addExtraPackage(\AppBundle\Entity\ExtraPackage $extraPackage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExtraPackage', [$extraPackage]);

        return parent::addExtraPackage($extraPackage);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExtraPackage(\AppBundle\Entity\ExtraPackage $extraPackage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExtraPackage', [$extraPackage]);

        return parent::removeExtraPackage($extraPackage);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtraPackage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtraPackage', []);

        return parent::getExtraPackage();
    }

    /**
     * {@inheritDoc}
     */
    public function setVegType($vegType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVegType', [$vegType]);

        return parent::setVegType($vegType);
    }

    /**
     * {@inheritDoc}
     */
    public function getVegType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVegType', []);

        return parent::getVegType();
    }

}
