<?php

namespace AppBundle\Repository;

/**
 * OrderTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
