<?php

namespace AppBundle\Repository;

/**
 * PriceVariationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceVariationRepository extends \Doctrine\ORM\EntityRepository
{
}
