<?php

namespace AppBundle\Repository;

/**
 * PromoUsageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoUsageRepository extends \Doctrine\ORM\EntityRepository
{
}
