<?php

namespace AppBundle\Repository;

/**
 * RestaurantsAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantsAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
