<?php

namespace AppBundle\Repository;

/**
 * RestaurantTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
