<?php

namespace AppBundle\Repository;

/**
 * SlotsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlotsRepository extends \Doctrine\ORM\EntityRepository
{
}
