<?php

namespace AppBundle\Repository;

/**
 * TransactionDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionDataRepository extends \Doctrine\ORM\EntityRepository
{
}
