services:
    function_helper:
        class: AppBundle\Helper\HelperFunction
        arguments: [ "@security.token_storage","@doctrine.orm.entity_manager" ,'@session', '@service_container']
    
    transaction_helper:
        class: AppBundle\Helper\TransactionHelper
        arguments: [ "@security.token_storage","@doctrine.orm.entity_manager" ,'@session', '@service_container', "@logger"]
        tags:
            - { name: monolog.logger, channel: transaction_logger }