<?php

namespace AppBundle\Repository;

/**
 * CustomerOrderItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerOrderItemsRepository extends \Doctrine\ORM\EntityRepository
{
}
