<?php

namespace AppBundle\Repository;

/**
 * DeliveryBoyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryBoyRepository extends \Doctrine\ORM\EntityRepository
{
}
