<?php

namespace AppBundle\Repository;

/**
 * DeliveryBoyAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryBoyAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
