<?php

namespace AppBundle\Repository;

/**
 * ExtraPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtraPackageRepository extends \Doctrine\ORM\EntityRepository
{
}
