<?php

namespace AppBundle\Repository;

/**
 * ShoppingListsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingListsRepository extends \Doctrine\ORM\EntityRepository
{
}
