<?php

namespace AppBundle\Repository;

/**
 * AdminAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
