<?php

namespace AppBundle\Repository;

/**
 * AdvertisementTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertisementTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
