<?php

namespace AppBundle\Repository;

/**
 * PriceVariationParentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceVariationParentRepository extends \Doctrine\ORM\EntityRepository
{
}
