<?php

namespace AppBundle\Repository;

/**
 * RestaurantRatingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantRatingsRepository extends \Doctrine\ORM\EntityRepository
{
}
