<?php

namespace AppBundle\Repository;

/**
 * returnLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class returnLogsRepository extends \Doctrine\ORM\EntityRepository
{
}
