<?php

namespace AppBundle\Repository;

/**
 * ShoppingListsNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingListsNameRepository extends \Doctrine\ORM\EntityRepository
{
}
