<?php

namespace AppBundle\Repository;

/**
 * SlotStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlotStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
