<?php

namespace AppBundle\Repository;

/**
 * SubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoryRepository extends \Doctrine\ORM\EntityRepository
{

 public function getCategoryList(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM sub_category c WHERE c.parent_category IS NULL '
            )
            ->getResult();
	}

}
