<?php

namespace AppBundle\Repository;

/**
 * WorkAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
